# Generated by Django 5.0.6 on 2024-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(default='')),
                ('nationality', models.CharField(default='', max_length=60)),
                ('gender', models.CharField(default=' ', max_length=10)),
                ('emergency_name', models.CharField(default='', max_length=100)),
                ('emergency_phone', models.IntegerField(default=1)),
                ('emergency_email', models.EmailField(default='', max_length=254)),
                ('id_mark', models.TextField(default='')),
                ('b_group', models.TextField(default='')),
                ('identity_mark', models.CharField(default='', max_length=100)),
                ('date_admission', models.DateField()),
                ('prefer_lan', models.CharField(default='', max_length=20)),
                ('father_occu', models.CharField(default='', max_length=30)),
                ('mother_occu', models.CharField(default='', max_length=30)),
                ('income', models.IntegerField(default='')),
                ('extra_activities', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, default='', upload_to='')),
                ('proof_address', models.FileField(blank=True, default='', upload_to='')),
                ('identity', models.FileField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
